### ISSUE TITLE
ユースケース考察

### ISSUE THREAD

**Issue by nakahashi** [nakahashi/koko.doc#1]
ユースケース書きました
![usecase](https://cloud.githubusercontent.com/assets/13581101/9589710/1373cb88-506b-11e5-8496-f17044df338e.png)

**Comment by SGA-kazuyoshi-inatomi** [comment]
関係ない話だけどUML何で書いた？Astahかな…？

**Comment by SGA-kazuyoshi-inatomi** [comment]
コアって何？
コアから機能設定に何をするのか分からないけど、コアが自発的に機能設定するの？

**Comment by nakahashi** [comment]
コアは(笑)、ビジネスロジックみたいなものです。どうどうと、そう書いた方が良かったですね。直しときます。

点線は依存関係のつもりで書いてますので、コアの動作は機能設定に依存してます、という意味ですね。

**Comment by nakahashi** [comment]
図は、興味があれども使う機会のなかったPlantUMLというライブラリで書いてみました。
テキストからUMLを吐いてくれるという代物です。↓

[PlantUML Cheat Sheet - Qiita](http://qiita.com/ogomr/items/0b5c4de7f38fd1482a48)

**Comment by nakahashi** [comment]
指摘に対応しました。

![usecase](https://cloud.githubusercontent.com/assets/13581101/9606824/a9e09192-5100-11e5-8446-fbc8be2cb0be.png)

**Comment by iKazuyoshi** [comment]
間違えて会社で使っているアカウントでポストしちゃった・・・
見なかったことにしてください。

**Comment by nakahashi** [comment]
PlantUML面白かったので、記事書いてみました。↓
[AtomとPlantUMLで爆速UMLモデリング - Qiita](http://qiita.com/nakahashi/items/3d88655f055ca6a2617c)

**Comment by iKazuyoshi** [comment]
PlantUMLね。
デフォルトってこんなだったっけ…

私もSony内で業務に普通に使用しています。
普及活動した結果、結構浸透してきました。

UseCaseとしてはシンプルで良いんじゃないでしょうか。
なんとなく伝わりました。

**Comment by iKazuyoshi** [comment]
Qiita見ました。
Windows10ならOneGet使ってみて欲しかったですね。
（Macどうしたの？）

**Comment by nakahashi** [comment]
それではユースケースはこれでクローズします。

**Comment by nakahashi** [comment]
OneGetはChocolatey用のパッケージを使うのにひと手間いるみたいで、また今度ということにしてました。。

Macは、涙なくしては語れない話ですがハードウェアが死にました。
熱帯夜にクラムシェルモードにして扇風機当てながら使ってたんですが、熱暴走の果てにいきなり電源が切れて、もう2度と立ち上がらないという orz
アップル銀座に持ち込んだら、マザーボード交換で3万円ということになり、とりあえず自分で分解してSSDだけ取り出して、データを救出させたところで放置してあります。。

**Comment by iKazuyoshi** [comment]
あら残念。。。我が家のMacは元気いっぱいです。
